{
  imports = [
    ./web-devicons.nix
    ./bufferline.nix
    ./treesitter.nix
    ./telescope.nix
    ./harpoon.nix
    ./undotree.nix
    ./lazygit.nix
    ./notify.nix
    ./noice.nix
    ./oil.nix
    ./cmp-cmdline.nix
    ./cmp.nix
    ./lsp.nix
    ./luasnip.nix
    ./lualine.nix
    ./autopairs.nix
    ./surround.nix
    ./commentary.nix
    ./vinegar.nix
    ./obsidian.nix
    ./godot.nix
  ];
}
